apiVersion: v1
kind: Service
metadata:
  name: {{ include "aska-server.fullname" . }}
  labels:
    {{- include "aska-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{ end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # Build the ports list based on values
    {{- range $port := .Values.service.ports }}
    - port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: {{ $port.protocol }}
      name: {{ $port.name }}
    {{- end }}
  selector:
    {{- include "aska-server.selectorLabels" . | nindent 4 }}

