{{- if .Values.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aska-server.fullname" . }}
  labels:
    app: {{ include "aska-server.name" . }}
    app.kubernetes.io/name: {{ include "aska-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "aska-server"
    {{- include "aska-server.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "aska-server.name" . }}
  replicas: 1
  {{- /* The if statement below is equivalent to {{- if $value }} but will also return true for 0. */ -}}
  {{- if not (has (quote .Values.global.revisionHistoryLimit) (list "" (quote ""))) }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aska-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "aska-server"
  template:
    metadata:
      labels:
        app: {{ include "aska-server.name" . }}
        app.kubernetes.io/name: {{ include "aska-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: "aska-server"
        {{- include "aska-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "aska-server.serviceAccountName" . }}
      {{- if hasKey .Values "automountServiceAccountToken" }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ template "aska-server.image" (tuple .Values.image $.Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # Server Configuration Environment Variables
            - name: TZ
              value: {{ .Values.serverConfig.timezone | quote }}
            - name: SERVER_NAME
              value: {{ .Values.serverConfig.serverName | quote }}
            {{- if .Values.serverConfig.password }}
            - name: PASSWORD
              value: {{ .Values.serverConfig.password | quote }}
            {{- end }}
            - name: SERVER_PORT
              value: {{ .Values.serverConfig.serverPort | quote }}
            - name: SERVER_QUERY_PORT
              value: {{ .Values.serverConfig.serverQueryPort | quote }}
            {{- if .Values.serverConfig.authenticationToken }}
            - name: AUTHENTICATION_TOKEN
              value: {{ .Values.serverConfig.authenticationToken | quote }}
            {{- end }}
            {{- if .Values.serverConfig.region }}
            - name: REGION
              value: {{ .Values.serverConfig.region | quote }}
            {{- end }}
            - name: KEEP_WORLD_ALIVE
              value: {{ .Values.serverConfig.keepWorldAlive | quote }}
            - name: AUTOSAVE_STYLE
              value: {{ .Values.serverConfig.autoSaveStyle | quote }}
            - name: CUSTOM_CONFIG
              value: {{ .Values.serverConfig.customConfig | quote }}
            - name: PUID
              value: {{ .Values.serverConfig.puid | quote }}
            - name: PGID
              value: {{ .Values.serverConfig.pgid | quote }}
            {{- with .Values.extraEnv }}
            # Additional custom environment variables
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- range $port := .Values.service.ports }}
            - name: {{ $port.name }}
              containerPort: {{ $port.targetPort }}
              protocol: {{ $port.protocol }}
            {{- end }}
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ include "aska-server.fullname" . }}
              mountPath: '/home/ubuntu/server_files'
            - name: tmp
              mountPath: /tmp
            {{- with .Values.additionalMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with  .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if not .Values.persistence.enabled }}
        - name: {{ include "aska-server.fullname" . }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.additionalVolumes }}
          {{- .Values.additionalVolumes | toYaml | nindent 6 }}
        {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "aska-server.fullname" . }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
      {{- if .Values.persistence.existingVolume }}
        volumeName: {{ .Values.persistence.existingVolume }}
      {{- end }}
      {{- if or .Values.persistence.matchLabels (.Values.persistence.matchExpressions) }}
        selector:
      {{- if .Values.persistence.matchLabels }}
          matchLabels:
        {{ toYaml .Values.persistence.matchLabels | indent 8 }}
      {{- end -}}
      {{- if .Values.persistence.matchExpressions }}
          matchExpressions:
          {{ toYaml .Values.persistence.matchExpressions | indent 8 }}
        {{- end -}}
      {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
      {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
      {{- end }}
  {{- end }}
{{- end }}

